# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: OCA modules for DMS.
repo_name: Document Management System modules for Odoo
repo_slug: dms
repo_website: https://github.com/OCA/dms
travis_apt_packages: []
travis_apt_sources: []
