# Copyright 2026 Keith Brandenburg
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "DMS Workspace UI",
    "summary": "Modern workspace interface for OCA DMS",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "category": "Document Management",
    "author": "Keith Brandenburg,Odoo Community Association (OCA)",
    "maintainers": ["windweaver828"],
    "website": "https://github.com/OCA/dms",
    "depends": ["dms"],
    "data": [
        "views/dms_file_views.xml",
        "views/menu.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dms_workspace_ui/static/src/js/dms_ui_core.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_directories.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_dialogs.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_registries.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_content_focus.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_focus_model.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_selection_model.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_workspace_service.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_workspace_ui.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_commands.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_actions.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_content_selection_model.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_content_keyboard_controller.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_content_browser_controller.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_native_controller.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_search_panel_controller.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_inspector.esm.js",
            "dms_workspace_ui/static/src/js/dms_workspace_ui.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_context_menu.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_search_panel_patch.esm.js",
            "dms_workspace_ui/static/src/js/dms_ui_drilldown_patch.esm.js",
            "dms_workspace_ui/static/src/xml/dms_ui_views.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_buttons.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_records.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_custom_browser.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_inspector.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_context_menu.xml",
            "dms_workspace_ui/static/src/xml/dms_ui_dialogs.xml",
            "dms_workspace_ui/static/src/scss/dms_ui_layout.scss",
            "dms_workspace_ui/static/src/scss/dms_ui_context_menu.scss",
            "dms_workspace_ui/static/src/scss/dms_ui_inspector.scss",
            "dms_workspace_ui/static/src/scss/dms_ui_browser.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
